# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

# load required packages
from pathlib import Path

INDIR = Path("input")
OUTDIR = Path("results")
RESOURCES = Path("resources")


# load configuration
# -----------------------------------------------------
configfile: "config/base.yaml"


# load rules
# -----------------------------------------------------
include: "rules/collate.smk"
include: "rules/align.smk"
include: "rules/phylo.smk"
include: "rules/snpdist.smk"
include: "rules/export.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        OUTDIR / "plots" / "global.pdf",
    default_target: True
