# Main entrypoint of the workflow.

# load required packages
from pathlib import Path

OUTDIR = Path(config["output"])
RESOURCES = Path("resources")


# load configuration
# -----------------------------------------------------
configfile: "config/base.yaml"
prefix = config["prefix"]

# load rules
# -----------------------------------------------------
include: "rules/collate.smk"
include: "rules/align.smk"
include: "rules/phylo.smk"
include: "rules/snpdist.smk"
include: "rules/export.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    default_target: True
    input:
        OUTDIR / "plots" / (prefix + "tree.pdf"),
        OUTDIR / "plots" / (prefix + "snpdist.pdf"),
        OUTDIR / "plots" / (prefix + "metrics.csv"),