sample_sheet: ".test/config/samples.tsv"

input:
  fasta:
    backbone: "input/backbone.fasta"
    samples: "input/input.fasta"
  meta:
    backbone: "input/backbone.tsv"
    samples: "input/input.tsv"

output: "results/"

align:
  reference: "input/reference.fasta"
  # change as required - recommended ~90% of complete genome including UTR.
  min_len: 10000

filter:
  strains_remove: "input/strains_remove.txt"
  strains_include: "input/strains_include.txt"

mask_utr:
  skip: False
  utr: "input/mask.utr.bed"

# mask positions before snpdist matrix is calculated
mask_snpdist:
  skip: False
  snpdist: "input/mask.snp.bed"

snpdist_cluster:
  skip: False
  list: "input/cluster.txt"

tree:
  model: "GTR+I+G"
  tree_params: "-B 1000 -bnni -alrt 1000"

refine:
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
    
ancestral:
    inference: "joint"

traits:
    columns:
      - country
      - region
    sampling_bias_correction: 3 # currently not used

plots:
  scripts:
    # path to scripts
    tree: "workflow/scripts/plot_tree.R"
    snpdist: "workflow/scripts/plot_snpdist.R"


auspice:
  strain_id_field: "strain"
  traits: ["Country", "Genotype"]
  config: "resources/auspice.json"
  clades: "resources/clades.tsv"
  colors: "resources/colors.tsv"
  export: "strain division location"