input:
  fasta:
    backbone: "input/n450/backbone.d8.fasta"
    samples: "input/n450/samples.d8.fasta"
  meta:
    backbone: "input/n450/backbone.tsv"
    samples: "input/n450/samples.tsv"

output: "results-d8/"

align:
  reference: "input/n450/reference_n450_d8.fasta"
  min_len: 440

plots:
  scripts:
    tree:
        path: "workflow/scripts/plot_tree_measles_n450.R"
        extra_args: "--offset_rate 0.3"

    snpdist: 
      path: "workflow/scripts/plot_snpdist.R"
      extra_args: "--font-size 8 --plot-type bottom --labels Designation"

filter:
  strains_remove: "input/empty.txt"
  strains_include: "input/empty.txt"
  
mask_utr:
  skip: True
  utr: "input/mask.utr.bed"

# mask positions before snpdist matrix is calculated
mask_snpdist:
  skip: True
  snpdist: "input/mask.snp.bed"

tree:
  model: "GTR+G"
  tree_params: "-B 1000 -bnni -alrt 1000"

refine:
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
    
ancestral:
    inference: "joint"

traits:
    columns:
      - country
      - region
    sampling_bias_correction: 3 # currently not used

auspice:
  strain_id_field: "notification_id"
  traits: ["place_of_acquisition_country", "Genotype"]
  config: "resources/auspice.json"
  clades: "resources/clades.tsv"
  colors: "resources/colors.tsv"
  export: "strain division location"