input:
  fasta:
    backbone: "input/backbone.d8.fasta"
    samples: "input/samples.d8.fasta"
  meta:
    backbone: "input/backbone.tsv"
    samples: "input/samples.tsv"

output: "results-d8/"

align:
  reference: "resources/reference_n450_d8.fasta"
  min_len: 440

plots:
  scripts:
    tree: "workflow/scripts/plot_tree.R"
    snpdist: "workflow/scripts/plot_snpdist.R"

filter:
  strains_remove: "resources/empty.txt"
  strains_include: "resources/empty.txt"
  
mask:
  skip: True
  utr: "resources/empty.bed"
  custom: "resources/empty.bed"

tree:
  model: "GTR+G"
  tree_params: "-B 1000 -bnni -alrt 1000"

refine:
    coalescent: "opt"
    date_inference: "marginal"
    clock_filter_iqd: 4
    
ancestral:
    inference: "joint"

traits:
    columns:
      - country
      - region
    sampling_bias_correction: 3 # currently not used

auspice:
  strain_id_field: "notification_id"
  traits: ["place_of_acquisition_country", "Genotype"]
  config: "resources/auspice.json"
  clades: "resources/clades.tsv"
  colors: "resources/colors.tsv"
  export: "strain division location"